name: Minecraft Bedrock Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenJDK
        run: choco install openjdk11

      - name: List files in current directory
        run: dir

      - name: Run Minecraft Bedrock Server
        run: |
          cd D:\a\minecraft-bedrock-server\minecraft-bedrock-server
          .\bedrock_server.exe
