name: Minecraft Bedrock Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Minecraft Bedrock Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          mkdir bedrock_server
          cp bedrock_server.tar.gz bedrock_server/
          cd bedrock_server
          tar -xzf bedrock_server.tar.gz
          ./bedrock_server
